# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  Repository: repository  # github repositories
  Books: books  # 豆瓣书单
  Links: links  # 友链
  About: about  # 关于

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/logo.png
  title: GeekBlog # 页面title
  favicon: /favicon.ico
  board: <p>Always Believe In Yourself!</p> # 站点公告
  copyright: false # 底部版权信息

# config
config:
  skin: theme-black # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: true # enable posts thumbnail, options: true, false
  excerpt_link: Read More

# Pagination
pagination:
  number: false
  prev: 
    alwayShow: true
  next:
    alwayShow: true

# Sidebar
sidebar: right
widgets:
  - board  
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
archive_type: 'monthly'
show_count: true

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  swiftype: # enter swiftype install key here
  baidu: false # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: true
  # 微信打赏
  wechatpay:
    qrcode: images/donate/wechat.jpg
    title: 微信支付
  # 支付宝打赏
  alipay: 
    qrcode: images/donate/alipay.jpg 
    title: 支付宝

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: true  # 是否启用分享
  sites: weibo,qq,wechat,facebook,twitter  # PC端显示的分享图标
  mobile_sites: weibo,qq,qzone  # 移动端显示的分享图标

# Github
github: 
  username: GeekGhc  # github username

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  type: livere  # 启用哪种评论系统
  disqus:  # enter disqus shortname here
  youyan: 
    uid: 1783844 # enter youyan uid 
  livere:
    uid: MTAyMC8zOTM1Ni8xNTg4Mw== # enter youyan uid 
  gitment:
    githubID: GeekGhc
    repo: geekghc.github.io
    ClientID: 4105f76eaa6963787045
    ClientSecret: 708d4513a9055fce41d48e0c9b325fece113c61d
    lazy: false
  valine: # Valine. https://valine.js.org
    appid:  # your leancloud application appid
    appkey:  # your leancloud application appkey
    notify: false # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: Just go go # comment box placeholder
    avatar: mm # gravatar style
    meta: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    visitor: false # Article reading statistic https://valine.js.org/visitor.html

# douban 豆瓣书单
# Api：
  # https://developers.douban.com/wiki/?title=book_v2 图书
  # https://developers.douban.com/wiki/?title=movie_v2 电影
# books：  
  # https://api.douban.com/v2/book/user/:name/collections?start=0&count=100 个人书单列表
# movies: 
  # https://api.douban.com/v2/movie/in_theaters 正在上映的电影
  # https://api.douban.com/v2/movie/coming_soon 即将上映的电影
  # https://api.douban.com/v2/movie/subject/:id 单个电影信息
  # https://api.douban.com/v2/movie/search?q={text} 电影搜索
douban:
  user: 155599714 # 豆瓣用户名
  start: 0 # 从哪一条记录开始
  count: 100 # 获取豆瓣书单数据条数
  
# PV
pv:
  busuanzi:
    enable: false  # 不蒜子统计
  leancloud:
    enable: true  # leancloud统计
    app_id: 3H2emKTOvxos7HRRrCibkchO-gzGzoHsz # leancloud <AppID>
    app_key: jSkuHSEoWJbYgMRelYTK6M8N # leancloud <AppKey>
        
# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计

# hexo-neat
neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: true
  exclude:
    - '*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics: 
  
# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  
  
# profile
profile:
  enabled: true # Whether to show profile bar
  avatar: images/me.jpg
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: GeekGhc
  author_title: Become A Better Programmer
  author_description: 个人简介。
  location: Shanghai, China
  follow: https://github.com/GeekGhc
  # Social Links
  social:
    links:
      github: https://github.com/GeekGhc
      weibo: http://weibo.com/geekghc
      twitter: https://twitter.com/JellyGavin
      google: https://plus.google.com/u/0/108390134136813492774
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills 
  skills:
    PHP: ★★★★★
    Golang: ★★★★☆
    Python: ★★★☆☆
    Java: ★★★☆☆
    C++: ★★☆☆☆
    HTML/CSS: ★★★★☆
    Javascript: ★★★★☆
    Swoole: ★★★★☆
    VueJs: ★★★★☆
    SQL: ★★★★☆
  # My Personal Links
  links:
    Github: https://github.com/GeekGhc
    Blog: http://jellybook.me
    微博: http://weibo.com/geekghc
    twitter: https://twitter.com/JellyGavin
  # My Personal Labels
  labels:
    - PHPer
    - 后端开发者
    - 前端爱好者
    - 全栈开发
    - Geek
  # My Personal Works
  works:
    codespace:
      link: https://www.geekghc.com
      date: 2018
  # My Personal Projects
  projects:
    GeekGhc/zhihu-app: https://github.com/GeekGhc/zhihu-app
    GeekGhc/ISpace: https://github.com/GeekGhc/ISpace
    GeekGhc/adminLTE-for-laravel: https://github.com/GeekGhc/adminLTE-for-laravel
    GeekGhc/dingo-api-demo: https://github.com/GeekGhc/dingo-api-demo